/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin_Screen;

import Model.dao.EmployeeInfoDAO;
import Model.dao.EmployeeTypeDAO;
import Model.to.EmployeeInfoTO;
import Model.to.EmployeeTypeTO;
import Utility.Validations;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.AncestorListener;

/**
 *
 * @author DELL
 */
public class Add_Employee_Detail extends javax.swing.JInternalFrame implements ActionListener, AncestorListener {

    /**
     * Creates new form Add_Employee_Detail
     */
    private List<EmployeeTypeTO> employees;
    public Add_Employee_Detail() {
        initComponents();
        bindEmployeetypeCombo();
    }
 private void bindEmployeetypeCombo(){
    employees = new EmployeeTypeDAO().getallRecord();
    jcbemptype.removeAllItems();
    jcbemptype.addItem("Choose any one type");
    if(employees!=null && employees.size()>0){
        for(EmployeeTypeTO emp:employees){
            jcbemptype.addItem(emp);
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfEMployeename = new javax.swing.JTextField();
        buttonAddEmployee = new javax.swing.JButton();
        lblEmployeeName = new javax.swing.JLabel();
        jtfEmployeeAdhaarcard = new javax.swing.JTextField();
        lblEmployeeAdhaarcard = new javax.swing.JLabel();
        jcbemptype = new javax.swing.JComboBox<>();
        lblchoosetype = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add new employee");

        jtfEMployeename.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        buttonAddEmployee.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        buttonAddEmployee.setText("Add Employee");
        buttonAddEmployee.addActionListener(this);

        lblEmployeeName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblEmployeeName.setText("Enter Employee Name:");

        jtfEmployeeAdhaarcard.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        lblEmployeeAdhaarcard.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblEmployeeAdhaarcard.setText("Adhaar card:");
        lblEmployeeAdhaarcard.addAncestorListener(this);

        jcbemptype.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jcbemptype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbemptype.addActionListener(this);

        lblchoosetype.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblchoosetype.setText("Choose type:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblEmployeeAdhaarcard, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblchoosetype, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfEMployeename, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfEmployeeAdhaarcard, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbemptype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(buttonAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbemptype, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblchoosetype, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfEMployeename, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEmployeeAdhaarcard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmployeeAdhaarcard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(buttonAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == buttonAddEmployee) {
            Add_Employee_Detail.this.buttonAddEmployeeActionPerformed(evt);
        }
        else if (evt.getSource() == jcbemptype) {
            Add_Employee_Detail.this.jcbemptypeActionPerformed(evt);
        }
    }

    public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
        if (evt.getSource() == lblEmployeeAdhaarcard) {
            Add_Employee_Detail.this.lblEmployeeAdhaarcardAncestorAdded(evt);
        }
    }

    public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
    }

    public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddEmployeeActionPerformed
        String message="";
        String Employeename = jtfEMployeename.getText().trim();
        String Employeeadhaar = jtfEmployeeAdhaarcard.getText().trim();
        if(Validations.isEmpty(Employeename)||Validations.isEmpty(Employeeadhaar))
        {
            message="Please fill all boxes";
        }else{
            EmployeeInfoTO record =new EmployeeInfoTO();
            record.setEmpName(Employeename);
            record.setAdhaarcard(Integer.parseInt(Employeeadhaar));
            EmployeeInfoDAO action = new EmployeeInfoDAO();
            if(action.insertRecord(record)){
                message ="Employee is inserted";
            }else{
                message="Insertion failure"+ action.getError_message();
            }
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_buttonAddEmployeeActionPerformed

    private void lblEmployeeAdhaarcardAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblEmployeeAdhaarcardAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblEmployeeAdhaarcardAncestorAdded

    private void jcbemptypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbemptypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbemptypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddEmployee;
    private javax.swing.JComboBox<java.lang.Object> jcbemptype;
    private javax.swing.JTextField jtfEMployeename;
    private javax.swing.JTextField jtfEmployeeAdhaarcard;
    private javax.swing.JLabel lblEmployeeAdhaarcard;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JLabel lblchoosetype;
    // End of variables declaration//GEN-END:variables
}
