/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin_Screen;

import Model.dao.DataConnection;
import Utility.Errorhandler;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import static Utility.Operations.openInternalFrame;

/**
 *
 * @author DELL
 */
public class AdminMainScreen extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form AdminMainScreen
     */
    public AdminMainScreen() {
        try{
            ImageIcon image=new ImageIcon(getClass().getResource("/Icons/icon.png"));
            setIconImage(image.getImage());
        }catch(Exception ex){
            Errorhandler.showErrorStack(ex);
        }
        initComponents();
        setSize(1000,650);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Deskpane = new javax.swing.JDesktopPane();
        Admin_menu_bar = new javax.swing.JMenuBar();
        Menu_Employee = new javax.swing.JMenu();
        Add_Employee = new javax.swing.JMenuItem();
        newEmployeeType = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DeskpaneLayout = new javax.swing.GroupLayout(Deskpane);
        Deskpane.setLayout(DeskpaneLayout);
        DeskpaneLayout.setHorizontalGroup(
            DeskpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1196, Short.MAX_VALUE)
        );
        DeskpaneLayout.setVerticalGroup(
            DeskpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );

        getContentPane().add(Deskpane, java.awt.BorderLayout.CENTER);

        Menu_Employee.setText("Employee");
        Menu_Employee.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N

        Add_Employee.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        Add_Employee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add.png"))); // NOI18N
        Add_Employee.setText("New Employee");
        Add_Employee.addActionListener(this);
        Menu_Employee.add(Add_Employee);

        newEmployeeType.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        newEmployeeType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add.png"))); // NOI18N
        newEmployeeType.setText("New Employee type");
        newEmployeeType.addActionListener(this);
        Menu_Employee.add(newEmployeeType);

        Admin_menu_bar.add(Menu_Employee);

        setJMenuBar(Admin_menu_bar);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == Add_Employee) {
            AdminMainScreen.this.Add_EmployeeActionPerformed(evt);
        }
        else if (evt.getSource() == newEmployeeType) {
            AdminMainScreen.this.newEmployeeTypeActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void Add_EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_EmployeeActionPerformed
        openInternalFrame(Deskpane, new Add_Employee_Detail());
    }//GEN-LAST:event_Add_EmployeeActionPerformed

    private void newEmployeeTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmployeeTypeActionPerformed
        openInternalFrame(Deskpane, new Add_Employee_Type());// TODO add your handling code here:
    }//GEN-LAST:event_newEmployeeTypeActionPerformed
    private void formWindowClosing(java.awt.event.WindowEvent evt){
        try{
        DataConnection.closeConnection();
        }catch(Exception ex){Errorhandler.showErrorStack(ex);}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Add_Employee;
    private javax.swing.JMenuBar Admin_menu_bar;
    private javax.swing.JDesktopPane Deskpane;
    private javax.swing.JMenu Menu_Employee;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem newEmployeeType;
    // End of variables declaration//GEN-END:variables
}
