/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin_Screen;

import Model.dao.RoomTypeDAO;
import Model.to.RoomTypeTO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class View_Rooms extends javax.swing.JInternalFrame {
    private List<RoomTypeTO> rooms;
    /**
     * Creates new form View_Rooms
     */
    public View_Rooms() {
        initComponents();
        bindviewRooms();
    }
    private void bindviewRooms(){
         String[] col_names ={"Room_ID","Room_Name","Room_Charges","Description"};
        Object[][] records=null;
        rooms= new RoomTypeDAO().getallRecord();
        if(rooms!=null && rooms.size()>0){
            records = new Object[rooms.size()][col_names.length];
            int index=0;
            for(RoomTypeTO rooms: rooms){
                records[index]=new Object[]{rooms.getTypeID(),rooms.getTypename(),rooms.getChargesperday(),rooms.getDescription()};
                index++;
            }
        }else{
            records = new Object[1][col_names.length];
            records[0]=new Object[]{"No Information available","No Information available"};
        }
        DefaultTableModel model =new DefaultTableModel(records, col_names);
        jtableRoomDetails.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtableRoomDetails = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("View Rooms Details");

        jtableRoomDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtableRoomDetails);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1056, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtableRoomDetails;
    // End of variables declaration//GEN-END:variables
}
