/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin_Screen;

import Model.dao.EmployeeInfoDAO;
import Model.to.EmployeeInfoTO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class ViewEmployee extends javax.swing.JInternalFrame {
    private List<EmployeeInfoTO> emp;
    /**
     * Creates new form ViewEmployee
     */
    public ViewEmployee() {
        initComponents();
        bindjtViewEmployee();
    }
    private void bindjtViewEmployee(){
        String[] col_names ={"Employee_ID","Employee_Name","Employee_typeName"};
        Object[][] records=null;
        emp= new EmployeeInfoDAO().getallRecord();
        if(emp!=null && emp.size()>0){
            records = new Object[emp.size()][col_names.length];
            int index=0;
            for(EmployeeInfoTO emp: emp){
                records[index]=new Object[]{emp.getEmpid(),emp.getEmpName(),emp.getEmptypename()};
                index++;
            }
        }else{
            records = new Object[1][col_names.length];
            records[0]=new Object[]{"No Information available","No Information available"};
        }
        DefaultTableModel model =new DefaultTableModel(records, col_names);
        jtEmployeeDetail.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtEmployeeDetail = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Employee details");

        jtEmployeeDetail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtEmployeeDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtEmployeeDetail);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtEmployeeDetail;
    // End of variables declaration//GEN-END:variables
}
