/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens;

import Admin_Screen.AdminMainScreen;
import Employee_Screen.Employee_Main_Screen;
import Model.dao.LoginInfoDAO;
import Model.to.LoginInfoTO;
import Utility.Errorhandler;
import Utility.Operations;
import Utility.Validations;
import java.awt.event.ActionListener;
import java.sql.Timestamp;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class LoginScreen extends javax.swing.JFrame implements ActionListener {

    public LoginScreen() {
        Operations.setApplicationIcon(this);
        initComponents();
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(jbtnlogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblpassword = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        jtfusername = new javax.swing.JTextField();
        jbtnlogin = new javax.swing.JButton();
        jpassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Screen");
        setResizable(false);

        lblpassword.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconfinder_Touch_131777.png"))); // NOI18N
        lblpassword.setText("Password:");

        lblusername.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblusername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/registration.png"))); // NOI18N
        lblusername.setText("User name:");

        jtfusername.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jbtnlogin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/done.png"))); // NOI18N
        jbtnlogin.setText("Login");
        jbtnlogin.addActionListener(this);

        jpassword.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfusername, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                            .addComponent(jpassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jbtnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(lblusername, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(581, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jtfusername, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jbtnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(lblusername, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(285, Short.MAX_VALUE)))
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == jbtnlogin) {
            LoginScreen.this.jbtnloginActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnloginActionPerformed
        String username =jtfusername.getText().trim();
        String password = new String(jpassword.getPassword());
        String message="";
        if(Validations.isEmpty(username)||Validations.isEmpty(password)){
            message="Please fill all boxes";
        }else
        {
            LoginInfoDAO action = new LoginInfoDAO();
            LoginInfoTO record = action.getRecord(username);
            if(record!=null){
                if(record.getPassword().equals(password)){
                    if(record.getRolename().equals("admin")){
                        AdminMainScreen ams = new AdminMainScreen();
                        ams.setVisible(true);
                        dispose();
                        if(record.getLastlogin()==null){
                            message="Hey!! You are welcome for the first time";
                        }else{
                            message="hey!! Your last login was:: "+record.getLastlogin();
                        }
                        record.setLastlogin(new Timestamp(System.currentTimeMillis()));
                        action.updateRecord(record);
                    }else if(record.getRolename().equals("employee")){
                        Employee_Main_Screen ems = new Employee_Main_Screen(username);
                        ems.setVisible(true);
                        dispose();
                        if(record.getLastlogin()==null){
                            message="Hey!! You are welcome for the first time";
                        }else{
                            message="hey!! Your last login was:: "+record.getLastlogin();
                        }
                        record.setLastlogin(new Timestamp(System.currentTimeMillis()));
                        action.updateRecord(record);
                    }else{
                        message="Insufficient privilage contact administrator\n";
                    }
                }else{
                    message ="Please fill valid username and password\n";
                }
            }else{
                message ="Please fill valid username and password\n";
            }
        } 
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_jbtnloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnlogin;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField jtfusername;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblusername;
    // End of variables declaration//GEN-END:variables
}
