/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Employee_Screen;

import Model.dao.BookingInfoDAO;
import Model.dao.CustomerInfoDAO;
import Model.dao.RoomTypeDAO;
import Model.to.BookingInfoTO;
import Model.to.CustomerInfoTO;
import Model.to.RoomTypeTO;
import Utility.Validations;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Add_Booking extends javax.swing.JInternalFrame implements ActionListener {
private List<RoomTypeTO> rooms;
private List<CustomerInfoTO> cus;
    /**
     * Creates new form Add_Customer
     */
    public Add_Booking() {
        initComponents();
        bindRoomtypeCombo();
        bindCustomerInfoCombo();
    }
     private void bindCustomerInfoCombo(){
    cus = new CustomerInfoDAO().getallRecord();
    jcbCustomerID.removeAllItems();
    jcbCustomerID.addItem("Choose any one type");
    if(cus!=null && cus.size()>0){
        for(CustomerInfoTO cus:cus){
            jcbCustomerID.addItem(cus);
        }
    }
}
 private void bindRoomtypeCombo(){
    rooms = new RoomTypeDAO().getallRecord();
    jcbRoomType.removeAllItems();
    jcbRoomType.addItem("Choose any one type");
    if(rooms!=null && rooms.size()>0){
        for(RoomTypeTO room:rooms){
            jcbRoomType.addItem(room);
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustomerName = new javax.swing.JLabel();
        jbtnAddCustomer = new javax.swing.JButton();
        lblNoOfPeople = new javax.swing.JLabel();
        jtfNoofPeople = new javax.swing.JTextField();
        lblRoomType = new javax.swing.JLabel();
        jcbRoomType = new javax.swing.JComboBox<>();
        lblBookingDate = new javax.swing.JLabel();
        jtfNoofRooms = new javax.swing.JTextField();
        lblNoOfRooms = new javax.swing.JLabel();
        jtfNoofDays = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbCustomerID = new javax.swing.JComboBox<>();
        lblNoOfDays = new javax.swing.JLabel();
        cdpBookingDate = new Controls.CurrentDatePanel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add new Bookinhg");

        lblCustomerName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCustomerName.setText("Choose Customer ID:");

        jbtnAddCustomer.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnAddCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/done.png"))); // NOI18N
        jbtnAddCustomer.setText("Add new Booking");
        jbtnAddCustomer.addActionListener(this);

        lblNoOfPeople.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblNoOfPeople.setText("Enter number of people:");

        jtfNoofPeople.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        lblRoomType.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblRoomType.setText("Choose Room Type:");

        jcbRoomType.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jcbRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblBookingDate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblBookingDate.setText("Enter Booking Date:");

        jtfNoofRooms.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        lblNoOfRooms.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblNoOfRooms.setText("Enter Number of Rooms:");

        jtfNoofDays.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/images (1).png"))); // NOI18N

        jcbCustomerID.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jcbCustomerID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblNoOfDays.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblNoOfDays.setText("Enter Number of Days:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel2)
                        .addGap(106, 106, 106)
                        .addComponent(jbtnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1)
                        .addGap(0, 599, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBookingDate, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136)
                                .addComponent(cdpBookingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNoOfDays, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                                    .addComponent(jtfNoofDays, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNoOfRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfNoofRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcbRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNoOfPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(182, 182, 182)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jcbCustomerID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtfNoofPeople, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNoOfPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNoofPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNoOfRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNoofRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNoOfDays, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNoofDays, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBookingDate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdpBookingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == jbtnAddCustomer) {
            Add_Booking.this.jbtnAddCustomerActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddCustomerActionPerformed

        String message="";
        boolean allvalid=true;
        if(jcbCustomerID.getSelectedIndex()==0){
            allvalid=false;
            message +="Please choose any CustomerID\n\n";
        } 
        if(jcbRoomType.getSelectedIndex()==0){
            allvalid=false;
            message +="Please choose any Room type\n\n";
        }
        String NumberofPeople =jtfNoofPeople.getText().trim();
        String NumberofRooms = jtfNoofRooms.getText().trim();
        String NumberofDays = jtfNoofDays.getText().trim();
        if(Validations.isEmpty(NumberofPeople)||Validations.isEmpty(NumberofRooms)||Validations.isEmpty(NumberofDays))
        {
            allvalid=false;
            message +="Please fill all boxes\n\n";
        }
        if(allvalid){
            BookingInfoTO rec = new BookingInfoTO();
            CustomerInfoTO cus = (CustomerInfoTO)jcbCustomerID.getSelectedItem();
            RoomTypeTO room = (RoomTypeTO)jcbRoomType.getSelectedItem();
            rec.setNoofdays(Integer.parseInt(NumberofDays));
            rec.setNoofpeople(Integer.parseInt(NumberofPeople));
            rec.setTotalrooms(Integer.parseInt(NumberofRooms));
            rec.setTypeID(room.getTypeID());
            rec.setCustomerid(cus.getCustomerid());
            BookingInfoDAO ac =new BookingInfoDAO();
           
            if(ac.insertRecord(rec)){
                message ="Welcome to our hotel!!!We wish you will like it!!";
            }else{
                message="Insertion failure"+ ac.getError_message();
            }
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_jbtnAddCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controls.CurrentDatePanel cdpBookingDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtnAddCustomer;
    private javax.swing.JComboBox<java.lang.Object> jcbCustomerID;
    private javax.swing.JComboBox<java.lang.Object> jcbRoomType;
    private javax.swing.JTextField jtfNoofDays;
    private javax.swing.JTextField jtfNoofPeople;
    private javax.swing.JTextField jtfNoofRooms;
    private javax.swing.JLabel lblBookingDate;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblNoOfDays;
    private javax.swing.JLabel lblNoOfPeople;
    private javax.swing.JLabel lblNoOfRooms;
    private javax.swing.JLabel lblRoomType;
    // End of variables declaration//GEN-END:variables
}
