/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Employee_Screen;

import Utility.Operations;
import java.awt.event.ActionListener;
import static Utility.Operations.openInternalFrame;
import static Utility.Operations.setApplicationIcon;

/**
 *
 * @author DELL
 */
public class Employee_Main_Screen extends javax.swing.JFrame implements ActionListener {
    private String username;

    public Employee_Main_Screen(String username) {
        this();
        this.username = username;
        setTitle("Welcome "+this.username+"!!! ");
    }
    /**
     * Creates new form Employee_Main_Screen
     */
    public Employee_Main_Screen() {
       setApplicationIcon(this);
        initComponents();
        setSize(1500, 900);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundDesktopPane1 = new Controls.BackgroundDesktopPane();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        deskpane = new Controls.BackgroundDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AddCustomer = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deskpane.setLayout(new java.awt.BorderLayout());
        getContentPane().add(deskpane, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Customers");
        jMenu1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N

        AddCustomer.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        AddCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add.png"))); // NOI18N
        AddCustomer.setText("New Booking");
        AddCustomer.addActionListener(this);
        jMenu1.add(AddCustomer);

        jMenuItem1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/registration.png"))); // NOI18N
        jMenuItem1.setText("New Customer");
        jMenuItem1.addActionListener(this);
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == AddCustomer) {
            Employee_Main_Screen.this.AddCustomerActionPerformed(evt);
        }
        else if (evt.getSource() == jMenuItem1) {
            Employee_Main_Screen.this.jMenuItem1ActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void AddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustomerActionPerformed
        openInternalFrame(deskpane, new Add_Booking());
    }//GEN-LAST:event_AddCustomerActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        openInternalFrame(deskpane, new Add_Customer());// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_Main_Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddCustomer;
    private Controls.BackgroundDesktopPane backgroundDesktopPane1;
    private Controls.BackgroundDesktopPane deskpane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
